# Generated by Django 2.2.2 on 2019-06-19 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_tracker', '0002_auto_20190619_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='onthedish',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
