# Generated by Django 2.2.2 on 2019-06-20 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash_tracker', '0003_onthedish_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnTheDish',
            new_name='ProductItem',
        ),
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash_tracker.Language'),
        ),
    ]
